// Copyright (c) 2025 Felix Kahle.
//
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
// LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
// OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

use bollard_model::index::{BerthIndex, VesselIndex};
use fixedbitset::FixedBitSet;

/// Distinguishes between mathematical artifacts and real physical schedules.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColumnKind {
    /// A mathematical construct used to ensure the initial basis is identity.
    ///
    /// Artificial columns have a very high cost (Phase 1 cost = 1.0, Phase 2 cost = Infinity).
    /// They represent "phantom" operations that satisfy constraints mathematically but
    /// are physically impossible. The goal of Phase 1 is to drive these out of the basis.
    Artificial,

    /// A valid physical schedule generated by the Pricing Oracle.
    ///
    /// These columns represent a feasible sequence of vessels on a specific berth.
    Regular,
}

/// Represents a generated variable (column) in the Master Problem.
///
/// In the context of the Branch-and-Price algorithm:
/// * **Primal View:** A `Column` is a variable $\lambda_j$ representing the selection of a specific schedule.
/// * **Matrix View:** It corresponds to a column vector $A_j$ in the constraint matrix, where $A_{ij} = 1$ if vessel $i$ is covered.
/// * **Physical View:** It is a concrete plan assigning a set of vessels to a specific berth at specific times.
#[derive(Debug, Clone, PartialEq)]
pub struct Column {
    /// The type of column (Artificial or Regular).
    kind: ColumnKind,

    /// The berth to which this schedule applies.
    /// For artificial columns, this is a placeholder (typically berth 0).
    berth_index: BerthIndex,

    /// A bitmask indicating which vessels are serviced by this schedule.
    /// This is the sparse representation of the column vector $A_j$.
    /// If bit $i$ is set, the constraint $\sum \lambda = 1$ for vessel $i$ is affected.
    covered_vessels: FixedBitSet,

    /// The precise schedule details (Vessel -> Start Time).
    /// Used to reconstruct the final `Solution` object.
    assignments: Vec<(VesselIndex, f64)>,

    /// The objective function coefficient $c_j$ (Weighted Flow Time).
    /// Note: During Phase 1 optimization, this cost is ignored in favor of minimizing artificial variables.
    cost: f64,
}

impl Column {
    /// Creates a new Artificial Column covering a single vessel.
    ///
    /// This is used to initialize the Simplex basis with an Identity Matrix.
    ///
    /// # Arguments
    /// * `vessel_index`: The index of the constraint (row) this artificial variable satisfies.
    /// * `total_vessels`: The total number of constraints (defines the size of the bitset).
    pub fn new_artificial(vessel_index: usize, total_vessels: usize) -> Self {
        debug_assert!(
            vessel_index < total_vessels,
            "Artificial column index {} out of bounds (N={})",
            vessel_index,
            total_vessels
        );

        let mut covered_vessels = FixedBitSet::with_capacity(total_vessels);
        covered_vessels.insert(vessel_index);

        Self {
            kind: ColumnKind::Artificial,
            // Berth index is irrelevant for artificial variables, using 0 as sentinel.
            berth_index: BerthIndex::new(0),
            covered_vessels,
            assignments: Vec::new(),
            cost: 0.0, // Cost is handled dynamically by the Phase manager.
        }
    }

    /// Creates a new Regular Column representing a valid physical schedule.
    ///
    /// # Arguments
    /// * `berth_index`: The berth performing the operations.
    /// * `assignments`: A list of (Vessel, Start Time) tuples.
    /// * `cost`: The calculated weighted flow time of this schedule.
    /// * `total_vessels`: The dimension of the constraint vector.
    pub fn new_regular(
        berth_index: BerthIndex,
        assignments: Vec<(VesselIndex, f64)>,
        cost: f64,
        total_vessels: usize,
    ) -> Self {
        let mut covered_vessels = FixedBitSet::with_capacity(total_vessels);

        for (vessel, _) in &assignments {
            let idx = vessel.get();
            debug_assert!(
                idx < total_vessels,
                "Assignment contains vessel index {} out of bounds (N={})",
                idx,
                total_vessels
            );
            covered_vessels.insert(idx);
        }

        Self {
            kind: ColumnKind::Regular,
            berth_index,
            covered_vessels,
            assignments,
            cost,
        }
    }

    // --- Accessors ---

    /// Returns the type of the column (Artificial or Regular).
    #[inline(always)]
    pub fn kind(&self) -> ColumnKind {
        self.kind
    }

    /// Returns the berth associated with this schedule.
    #[inline(always)]
    pub fn berth_index(&self) -> BerthIndex {
        self.berth_index
    }

    /// Returns the bitmask of covered vessels ($A_j$).
    #[inline(always)]
    pub fn covered_vessels(&self) -> &FixedBitSet {
        &self.covered_vessels
    }

    /// Returns the physical assignments in this schedule.
    #[inline(always)]
    pub fn assignments(&self) -> &[(VesselIndex, f64)] {
        &self.assignments
    }

    /// Returns the objective cost ($c_j$) of this schedule.
    #[inline(always)]
    pub fn cost(&self) -> f64 {
        self.cost
    }

    /// Returns the number of vessels covered by this column (Hamming weight).
    #[inline(always)]
    pub fn len(&self) -> usize {
        self.covered_vessels.count_ones(..)
    }

    /// Returns true if this column covers no vessels (should not happen in valid logic).
    #[inline(always)]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_artificial_column_properties() {
        let col = Column::new_artificial(5, 10);

        assert_eq!(col.kind(), ColumnKind::Artificial);
        assert_eq!(col.cost(), 0.0); // Raw cost is 0, effective cost depends on phase
        assert_eq!(col.assignments().len(), 0);
        assert_eq!(col.len(), 1);

        // Bitset verification
        assert!(col.covered_vessels().contains(5));
        assert!(!col.covered_vessels().contains(4));
    }

    #[test]
    fn test_regular_column_properties() {
        let total_vessels = 10;
        let assignments = vec![(VesselIndex::new(1), 100.0), (VesselIndex::new(3), 200.0)];

        let col = Column::new_regular(
            BerthIndex::new(2),
            assignments.clone(),
            500.0,
            total_vessels,
        );

        assert_eq!(col.kind(), ColumnKind::Regular);
        assert_eq!(col.berth_index().get(), 2);
        assert_eq!(col.cost(), 500.0);
        assert_eq!(col.assignments(), &assignments);

        // Bitset verification
        assert_eq!(col.len(), 2);
        assert!(col.covered_vessels().contains(1));
        assert!(col.covered_vessels().contains(3));
        assert!(!col.covered_vessels().contains(2));
    }

    #[test]
    #[cfg(debug_assertions)]
    #[should_panic(expected = "out of bounds")]
    fn test_panic_on_invalid_vessel_index() {
        // This should panic in debug mode
        let _ = Column::new_artificial(10, 5);
    }
}
